# Generated by Django 5.0.6 on 2024-06-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RRF', models.CharField(max_length=13)),
                ('Nombre', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.CharField(max_length=50)),
                ('Web', models.CharField(max_length=50)),
                ('Descuento', models.FloatField()),
            ],
        ),
    ]
