# Generated by Django 5.0.6 on 2024-06-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
