# Generated by Django 5.0.6 on 2024-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellidos',
            new_name='apellido_Materno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='apellido_Paterno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_cliente',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono',
            new_name='telefono_Móvil',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dirección',
            field=models.CharField(default='Sin especificar', max_length=100),
            preserve_default=False,
        ),
    ]
