# Generated by Django 5.0.6 on 2024-06-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_apellidos_cliente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono_Móvil',
            new_name='telefono_Movil',
        ),
    ]
