# Generated by Django 5.0.6 on 2024-06-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_dirección_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido_Materno',
            new_name='Apellido_Materno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido_Paterno',
            new_name='Apellido_Paterno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ciudad',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='Correo',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='direccion',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='puntos',
            new_name='Puntos',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefono_Movil',
            new_name='Telefono_Movil',
        ),
    ]
