# Generated by Django 5.0.6 on 2024-06-17 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_options_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SumarPuntos',
        ),
    ]
