# Generated by Django 5.0.6 on 2024-06-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_delete_sumarpuntos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='Lista de clientes',
        ),
    ]
