# Generated by Django 5.0.6 on 2024-06-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Premio', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
            ],
        ),
    ]
