# Generated by Django 5.0.6 on 2024-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premios',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='premios/media'),
        ),
    ]
