# Generated by Django 5.0.6 on 2024-06-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0002_premios_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premios',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='premios/'),
        ),
    ]
