# Generated by Django 5.0.6 on 2024-06-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premios', '0003_alter_premios_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Premios',
            new_name='Premio',
        ),
    ]
